version: "3.9"

services:
  mongodb:
    image: mongo:7
    container_name: fdgsms-mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: FDGadmin
      MONGO_INITDB_ROOT_PASSWORD: fdgmongo123
    volumes:
      - mongo_data:/data/db
    networks:
      - fdgsms-net

  server:
    build: ./server
    container_name: fdgsms-server
    restart: unless-stopped
    ports:
      - "5000:4000"
    environment:
      PORT: 4000
      MONGO_URI: mongodb://FDGadmin:fdgmongo123@mongodb:27017/fdgsms?authSource=admin
      CLIENT_URL: https://fdgsms.filldesigngroup.cloud

      JWT_SECRET: 
      ADMIN_EMAIL: 
      ADMIN_PASSWORD: 

      TWILIO_ACCOUNT_SID: 
      TWILIO_AUTH_TOKEN: 
      TWILIO_PHONE_NUMBER: 

    depends_on:
      - mongodb
    networks:
      - fdgsms-net
      - n8n_default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=n8n_default"
      - "traefik.http.routers.fdgsms-api.rule=Host(`fdgsms.filldesigngroup.cloud`) && PathPrefix(`/api`)"
      - "traefik.http.routers.fdgsms-api.entrypoints=web,websecure"
      - "traefik.http.routers.fdgsms-api.tls=true"
      - "traefik.http.routers.fdgsms-api.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.fdgsms-api.priority=100"
      - "traefik.http.services.fdgsms-api.loadbalancer.server.port=4000"

  client:
    build:
      context: ./client
      args:
        VITE_API_URL: /api
    container_name: fdgsms-client
    restart: unless-stopped
    ports:
      - "5175:3000"
    depends_on:
      - server
    networks:
      - fdgsms-net
      - n8n_default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=n8n_default"
      - "traefik.http.routers.fdgsms.rule=Host(`fdgsms.filldesigngroup.cloud`)"
      - "traefik.http.routers.fdgsms.entrypoints=web,websecure"
      - "traefik.http.routers.fdgsms.tls=true"
      - "traefik.http.routers.fdgsms.tls.certresolver=mytlschallenge"
      - "traefik.http.services.fdgsms.loadbalancer.server.port=3000"

networks:
  fdgsms-net:
    driver: bridge
  n8n_default:
    external: true

volumes:
  mongo_data: